config/routes.rb
Rails.application.routes.draw do
  get 'profiles/index'

  get 'profiles/show'

  devise_for :users
  resources :tweets do
    resource :like
  end

  resources :relationships

  root 'tweets#index'
  get 'profiles' => 'profiles#index'
  get 'profiles/:id' => 'profiles#show', as: :profile

end

app/models/like.rb
class Like < ActiveRecord::Base
	belongs_to :user
	belongs_to :tweet
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
	belongs_to :user
	belongs_to :friend, class_name: "User"
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  has_many :likes

  validates :message, presence: true
  validates :message, length: {maximum: 140, too_long: "A tweet is only 150 characters max."}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :image, styles:{medium: "300x300>", thumb: "100x100>"}, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  has_many :tweets
  has_many :likes
  has_many :relationships
  has_many :friends, through: :relationships

  has_many :inverse_relationships, :class_name => "Relationship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_relationships, :source => :user

  validates :username, presence: true, uniqueness: true

  def likes?(tweet)
  	tweet.likes.where(user_id: id).any?
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, :name, :username, :bio, :location, :image) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :current_password, :name, :username, :bio, :location, :image) }
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :authenticate_user!
	before_action :set_tweet

	def create
		@tweet.likeswhere(user_id: current_user.id).first_or_create

		respond_to do |format|
			format.html{redirect_to request.referrer}
		end
	end

	def destroy
		@tweet.likes.where(user_id: current_user.id).destroy_all
		respond_to do |format|
			format.html{redirect_to request.referrer}
		end
	end
	
	private
	
	def set_tweet
		@tweet = Tweet.find(params[:tweet_id])
	end


end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
  	@users = User.all
  end

  def show
  	@user = User.find(params[:id])
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	def create
		@relationship = current_user.relationships.build(:friend_id => params[:friend_id])
		if @relationship.save
			flash[:notice] = "Followed successfully."
			redirect_to profile_path(current_user.id)
		else
			flash[:notice] = "Unable to follow."
			redirect_to root_path
		end
	end

	def destroy
		@relationship = current_user.relationships.find(params[:id])
		@relationship.destroy
		flash[:notice] = "No longer following."
		redirect_to profile_path(current_user.id)
	end

		private

		def relationship_params
			params.require(relationship).permit(:user_id, :friend_id)
		end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

	before_action :set_tweet, only: [:show, :edit, :update, :destroy]

	before_filter :authenticate_user!

	def index
		@tweets = Tweet.all
	end

	def new
		@tweet = Tweet.new
	end

	def show
	end

	def create
		@tweet = Tweet.new(tweet_params)

		respond_to do |format|
			if @tweet.save
				format.html {redirect_to @tweet, notice: 'tweet was successfully created.'}
			else
				format.html {render :new}
			end
		end
	end

	def update
		respond_to do |format|
			if @tweet.update(tweet_params)
				format.html {redirect_to @tweet, notice:'Tweet was successfully updated'}
			else
				format.html {render :edit}
			end
		end
	end

	def destroy
		@tweet.destroy
		respond_to do |format|
			format.html {redirect_to tweets_url, notice: 'Tweet was successfully deleted'}
		end
	end

	private

	def set_tweet
		@tweet = Tweet.find(params[:id])
	end

	def tweet_params
		params.require(:tweet).permit(:message, :user_id)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterApp</title>
  
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<nav class="navbar navbar-default">
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <div class="container-fluid">
	      <ul class="nav navbar-nav">
	        <li><%= link_to 'Home', tweets_path %></li>
	        <li><%= link_to 'New Tweet', new_tweet_path %></li>
          <li><%= link_to 'All Users', profiles_path %></li>
	        <!-- <li role="separator" class="divider"></li> -->
          
          <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
	      </ul>
      
    </div>
  </div>
</nav>




<div class="container">
<%= yield %>
</div>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js' %>
</body>
</html>

app/views/profiles/index.html.erb
<h1>All Users</h1>

<% @users.each do |user| %>
	<%= image_tag user.image.url(:thumb) %><br>
	<%= link_to user.username, profile_path(user) %><br>

	<% end %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
	<div class="col-xs-4">
		<%= image_tag @user.image.url(:medium) %>
		<h3><%= @user.name %></h3>
		<h5><%= @user.username %></h5>
		<p><%= @user.bio %></p>
		<p><%= @user.location %></p>
		<p>Joined on <%= @user.created_at.strftime("%B %Y") %></p>
		<%= @user.relationships.count %> Following <br>
		<% @user.relationships.each do |relationship| %>
		<%= link_to relationship.friend.name, profiles_path(relationship.friend)%>
		<% end %>

		<br>
		<br>

		<%= pluralize(@user.inverse_relationships.count, "Follower") %>
		<br>
		<% @user.inverse_friends.each do |friend| %>
		<%= link_to friend.name, profile_path(friend) %>
		<br>
		<% end %>
	</div>
	<div class="col-xs-7">
		<div class="panel panel-default">
			<% @user.tweets.each do |tweet| %>
			<div class="panel-body">
				<strong><%= tweet.user.username %></strong><small> tweeted <%= time_ago_in_words(tweet.created_at) %> ago </small><br><br>
				<%= tweet.message %>
			</div>
			<% end %>
		</div>
	</div>
</div>

<% if current_user.id == @user.id %>
<p><%= link_to "All Users", profiles_path %></p>
<% else %>

	<% if current_user.friends.include?(@user) %>
		<%= link_to "Unfollow", relationships_path(current_user.relationships.find_by_friend_id(@user)), :method => :delete %>
	<% else %>
	<%= link_to "Follow", relationships_path(:friend_id => @user), method: :post %>
	<% end %>
<% end %>

app/views/shared/_likes.html.erb
<% if current_user.likes?(@tweet) %>
	<%= link_to "Unlike", tweet_like_path(@tweet), method: :delete %>
<% else %>
	<%= link_to "like", tweet_like_path(@tweet), method: :post %>
<% end %>

<%= @tweet.likes.count %>
<p>Liked by: </p>

<% @tweet.likes.each do |like| %>
	<br>
	<%= like.user.username %>
	<br>
<% end %>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
	<% if @tweet.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@tweet.errors.count, "error") %>
			prohibited this tweet from being saved:</h2>

			<ul>
				<% @tweet.errors.full_message.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.label :message %><br>
		<%= f.text_field :message %>
	</div>

	<div class="field cant-see-me">
		<%= f.label :user_id %><br>
		<%= f.text_field :user_id, value: current_user.id %>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Edit Tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<table>
	<thead>
		<tr>
			<th>Message</th>
			<th>User</th>
			<th colspan="3"></th>
		</tr>
	</thead>
	<tbody>
		<% @tweets.reverse.each do |tweet| %>
		
			<tr>
				<td><%= tweet.message %></td>
				<td><%= link_to tweet.user.username, profile_path(tweet.user) %></td>
				<td><%= link_to 'Show', tweet %></td>
				<td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
				<td><%= link_to 'Destroy', tweet, method: :delete, data: {confirm: 'Are you sure?'} %></td>
			</tr>
		
			<% end %>

			<div class="row">
				
		</tbody>
	</table>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1> New Tweet </h1>

<%= render 'form' %>

<%= link_to 'back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<strong>Message:</strong>
	<%= @tweet.message %>
</p>

<p>
	<strong>User:</strong>
	<%= @tweet.user.username %>
</p>

<%= render "shared/likes" %>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>